# Generated by Django 5.1.2 on 2024-10-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_Name', models.CharField(max_length=50)),
                ('student_Address', models.CharField(max_length=100)),
                ('student_Dob', models.DateTimeField(default=True, null=True)),
                ('student_Father_Name', models.CharField(max_length=50)),
                ('student_Image', models.ImageField(upload_to='static/')),
                ('student_Description', models.TextField(default='')),
            ],
        ),
    ]
